name: go
on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  build-test:
    uses: tenfyzhong/workflows/.github/workflows/go-build-test.yml@feat-go-parse-version
    with:
      path: "."
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
