name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: tag
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Echo tag
        run: echo ${{ steps.tag.outputs.version }}
      - uses: tenfyzhong/workflows/.github/workflows/release-go.yml@main
        env:
          VERSION: ${{ steps.tag.outputs.version }}
        with:
          bin-path: "./cmd/st2"
          command: "st2"
          build-option: "-ldflags \"-X 'github.com/tenfyzhong/st2/cmd/st2/config.Version=${VERSION}'\""

